name: Publish to npm and GPR

on:
  release:
    types: [created]

jobs:
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "10.x"
        registry-url: https://registry.npmjs.org/
    - run: yarn install
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
    - uses: actions/setup-node@v1
      with:
        registry-url: "https://npm.pkg.github.com"
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
